//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
// Parameters:

row_major float4x4 ModelViewProj : register(c0);
row_major float4x4 TESR_InvViewProjectionTransform : register(c35);

// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   ModelViewProj[0] const_0        1
//   ModelViewProj[1] const_1        1
//   ModelViewProj[2] const_2        1
//   ModelViewProj[3] const_3        1
//


// Structures:

struct VS_INPUT {
    float4 LPOSITION : POSITION;
    float4 LTEXCOORD_0 : TEXCOORD0;
};

struct VS_OUTPUT {
    float4 position : POSITION;
    float2 texcoord_0 : TEXCOORD0;
	float4 texcoord_6 : TEXCOORD6;
};

// Code:

VS_OUTPUT main(VS_INPUT IN) {
    VS_OUTPUT OUT;

	float4 r0;
	float4 r1;
	
	r0 = mul(ModelViewProj, IN.LPOSITION);
    r1 = mul(r0, TESR_InvViewProjectionTransform);
	
	OUT.position = r0;
    OUT.texcoord_0.xy = IN.LTEXCOORD_0.xy;
	OUT.texcoord_6 = r1;
	
    return OUT;
};

// approximately 5 instruction slots used