//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
// Parameters:

// placed water surface shader 

float4 EyePos : register(c1);
float4 ShallowColor : register(c2);
float4 DeepColor : register(c3);
float4 ReflectionColor : register(c4);
float4 FresnelRI : register(c5);
float4 VarAmounts : register(c8);
float4 FogParam : register(c9);
float4 FogColor : register(c10);
float2 DepthFalloff : register(c11);
float4 SunDir : register(c12);
float4 SunColor : register(c13);
float4 TESR_WaveParams : register(c14);
float4 TESR_WaterVolume : register(c15);

sampler2D RefractionMap : register(s1);
sampler2D NoiseMap : register(s2);
sampler2D DepthMap : register(s4);

// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   EyePos          const_1       1
//   ShallowColor    const_2       1
//   DeepColor       const_3       1
//   ReflectionColor const_4       1
//   FresnelRI       const_5       1
//   VarAmounts      const_8       1
//   FogParam        const_9       1
//   FogColor        const_10      1
//   DepthFalloff    const_11      1
//   SunDir          const_12      1
//   SunColor        const_13      1
//   RefractionMap   texture_1       1
//   NoiseMap        texture_2       1
//   DepthMap        texture_4       1
//


// Structures:

struct VS_INPUT {
    float4 LTEXCOORD_0 : TEXCOORD0_centroid;
    float4 LTEXCOORD_1 : TEXCOORD1_centroid;
    float4 LTEXCOORD_2 : TEXCOORD2_centroid;
    float4 LTEXCOORD_3 : TEXCOORD3_centroid;
    float4 LTEXCOORD_4 : TEXCOORD4_centroid;
    float4 LTEXCOORD_5 : TEXCOORD5_centroid;
    float4 LTEXCOORD_6 : TEXCOORD6;
    float2 LTEXCOORD_7 : TEXCOORD7;
};

struct VS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

VS_OUTPUT main(VS_INPUT IN) {
    VS_OUTPUT OUT;

#define	expand(v)		(((v) - 0.5) / 0.5)
#define	compress(v)		(((v) * 0.5) + 0.5)
#define	shade(n, l)		max(dot(n, l), 0)
#define	shades(n, l)		saturate(dot(n, l))
#define	weight(v)		dot(v, 1)
#define	sqr(v)			((v) * (v))

    const float4 const_14 = {-0.569999993, 0.819999993, 0, 100};
    const int4 const_6 = {0, 2, -1, 1};
    const float4 const_7 = {-4, 4, 1, -9.99999975e-005};

    float2 q12;
    float1 q18;
    float1 q3;
    float1 q30;
    float1 q4;
    float1 q6;
    float1 q7;
    float4 r0;
    float4 r1;
    float3 r2;
    float4 r3;
    float4 r4;
    float3 r5;
    float4 r6;
	float choppiness = TESR_WaveParams.x;
	float waveWidth = TESR_WaveParams.y;
	float reflectivity = TESR_WaveParams.w;
	float turbidity = TESR_WaterVolume.z;
	
    r3.xyzw = tex2D(NoiseMap, IN.LTEXCOORD_7.xy * waveWidth);
    r1.w = dot(IN.LTEXCOORD_5.xyzw, IN.LTEXCOORD_1.xyzw);
    r1.y = r1.w - dot(IN.LTEXCOORD_3.xyzw, IN.LTEXCOORD_1.xyzw);
    r1.z = dot(IN.LTEXCOORD_4.xyzw, IN.LTEXCOORD_1.xyzw);
    r1.x = dot(IN.LTEXCOORD_2.xyzw, IN.LTEXCOORD_1.xyzw);
    r0.xyzw = tex2Dproj(DepthMap, r1.xyzw);
    r0.z = saturate((r0.y - DepthFalloff.x) / (DepthFalloff.y - DepthFalloff.x));
    r1.xyz = const_7.xyz;
    r2.xyz = EyePos.xyz - IN.LTEXCOORD_0.xyz;
    r4.xy = saturate(lerp(r0.xy * turbidity, 1, 1 - saturate(1 - ((length(r2.xy) - 4096) * 0.000244140625))));
    q3.x = 1 - saturate((FogParam.z - (r4.x * FogParam.z)) / FogParam.w);
    r3.xyz = (r0.z * expand(r3.xyz) * choppiness) + const_6.xxw;
    r3.xy = saturate(1 - ((length(r2.xy) - 4096) * 0.000244140625)) * r3.xy;
    r5.xyz = normalize(r3.xyz);
    q7.x = pow(abs(shades(reflect(-normalize(r2.xyz), r5.xyz), SunDir.xyz)), VarAmounts.x);
    q6.x = pow(abs(saturate(dot(r5.xz, const_14.xy) + 0)), 100);
    q4.x = 1 - shades(normalize(r2.xyz), r5.xyz);
    r3.zw = (IN.LTEXCOORD_1.z * const_6.wx) + const_6.xw;
    q12.xy = ((r0.y * r0.z) * ((saturate(length(r2.xy) * 0.0002) * (r1.x + VarAmounts.w)) + 4)) * r5.xy;
    r0.y = length(r2.xyz);
    r0.x = r4.y + r0.y;
    r0.xy = saturate((FogParam.x - r0.xy) / FogParam.y);
    r1.x = pow(abs(1 - r0.y), FresnelRI.y);
    q18.x = shades(normalize(r1.zyz * SunDir.xyz), r5.xyz);
    q30.x = pow(abs(1 - r0.x), FresnelRI.y);
    r3.xy = ((1.0 / IN.LTEXCOORD_0.w) * q12.xy) + IN.LTEXCOORD_1.xy;
    r6.w = dot(IN.LTEXCOORD_5.xyzw, r3.xyzw);
    r6.y = r6.w - dot(IN.LTEXCOORD_3.xyzw, r3.xyzw);
    r6.z = dot(IN.LTEXCOORD_4.xyzw, r3.xyzw);
    r6.x = dot(IN.LTEXCOORD_2.xyzw, r3.xyzw);
    r3.xyzw = tex2Dproj(RefractionMap, r6.xyzw);
    r0.xyw = (r3.xyz - (q30.x * FogColor.xyz)) / (1 - (q30.x - 9.99999975e-005));
    r3.xyz = (r4.y * (DeepColor.rgb - ShallowColor.rgb)) + ShallowColor.rgb;
    r0.xyz = ((r0.z * (q3.x * FogColor.a)) * ((q18.x * r3.xyz) - r0.xyw)) + r0.xyw;
    r0.w = r4.x * lerp(FresnelRI.x, 1, q4.x * sqr(sqr(q4.x)));
    r4.xzw = q18.x * r3.xyz;
    r1.yzw = (r0.w * (ReflectionColor.xyz - (r3.xyz * q18.x))) + r4.xzw;
    r0.xyz = saturate((SunDir.w * ((q6.x + q7.x) * SunColor.rgb)) + lerp(r0.xyz, r1.yzw, r4.y));
    OUT.color_0.a = IN.LTEXCOORD_6.w;
    OUT.color_0.rgb = (r1.x * (FogColor.xyz - r0.xyz)) + r0.xyz;

    return OUT;
	
};