//
// Generated by Microsoft (R) HLSL Shader Compiler 9.23.949.2378
//
// Parameters:

// water height for auto water

float fNoiseScale : register(c3);
float4 TESR_GameTime : register(c6);
float4 TESR_WaveParams : register(c7);

sampler2D NoiseMap : register(s0);
sampler3D TESR_Water : register(s1) < string ResourceName = "Water\water_NRM.dds"; > = sampler_state { ADDRESSU = WRAP; ADDRESSV = WRAP; ADDRESSW = WRAP; MAGFILTER = LINEAR; MINFILTER = LINEAR; MIPFILTER = LINEAR; } ;

// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   fNoiseScale  const_3       1
//   NoiseMap     texture_0       1
//


// Structures:

struct VS_INPUT {
    float2 texcoord_0 : TEXCOORD0;
};

struct VS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

VS_OUTPUT main(VS_INPUT IN) {
    VS_OUTPUT OUT;

    float frame = TESR_GameTime.z * TESR_WaveParams.z;
    float4 HeightMap = tex3D(TESR_Water, float3(IN.texcoord_0.xy, frac(frame)));

	OUT.color_0 = HeightMap;
    return OUT;
	
};
