//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
// Parameters:

float4 PSLightColor[4] : register(c2);
float4 Toggles : register(c7);
float4 TESR_ShadowData : register(c8);

sampler2D NormalMap : register(s0);
sampler2D TESR_ShadowMapBufferNear : register(s6) = sampler_state { ADDRESSU = CLAMP; ADDRESSV = CLAMP; MAGFILTER = LINEAR; MINFILTER = LINEAR; MIPFILTER = LINEAR; };
sampler2D TESR_ShadowMapBufferFar : register(s7) = sampler_state { ADDRESSU = CLAMP; ADDRESSV = CLAMP; MAGFILTER = LINEAR; MINFILTER = LINEAR; MIPFILTER = LINEAR; };

// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   PSLightColor[0] const_2        1
//   Toggles      const_7       1
//   NormalMap    texture_0       1
//


// Structures:

struct VS_INPUT {
    float2 NormalUV : TEXCOORD0;
    float3 texcoord_1 : TEXCOORD1_centroid;
    float3 texcoord_3 : TEXCOORD3_centroid;
	float4 texcoord_6 : TEXCOORD6;
	float4 texcoord_7 : TEXCOORD7;
};

struct VS_OUTPUT {
    float4 color_0 : COLOR0;
};

#include "..\Includes\Shadow.hlsl"

VS_OUTPUT main(VS_INPUT IN) {
    VS_OUTPUT OUT;

#define	expand(v)		(((v) - 0.5) / 0.5)
#define	compress(v)		(((v) * 0.5) + 0.5)
#define	shade(n, l)		max(dot(n, l), 0)
#define	shades(n, l)	saturate(dot(n, l))
#define	weight(v)		dot(v, 1)
#define	sqr(v)			((v) * (v))

    float4 noxel0;
    float1 q3;
    float3 q4;
    float1 q9;
	float3 q2;
	
    noxel0.xyzw = tex2D(NormalMap, IN.NormalUV.xy);
	q2.xyz = normalize(expand(noxel0.xyz));
    q9.x = noxel0.w * pow(abs(shades(q2.xyz, normalize(IN.texcoord_3.xyz))), Toggles.z);
    q3.x = dot(q2.xyz, IN.texcoord_1.xyz);
    q4.xyz = GetLightAmount(IN.texcoord_6, IN.texcoord_7) * (0.2 >= q3.x ? (q9.x * max(q3.x + 0.5, 0)) : q9.x) * PSLightColor[0].rgb;
    OUT.color_0.a = weight(q4.xyz);
    OUT.color_0.rgb = saturate(q4.xyz);
    return OUT;
	
};

// approximately 27 instruction slots used (1 texture, 26 arithmetic)