#pragma once
void ReadyWeaponHook();
void ActorReadyWeaponSittingHook();
void PlayerAttackHook();
void HittingMountedCreatureHook();
void HideWeaponHook();
void BowEquipHook();
void BowUnequipHook();
void AnimControllerHook();
void HorsePaletteHook();
