# Main configuration settings
[Main]
RemoveUnderwater = true
RemovePrecipitations = true
RemoveFogPass = false
MemoryTextureManagement = true
GrassMode = true
# Replace the intro video and the main menu background video with a custom one
ReplaceIntroAndMainMenuBackgroundVideos = false
AnisotropicFilter = 4
ScreenshotKey = 87
FarPlaneDistance = 283840.0
TestDirectionLight = false

# Water (non shader related) settings
[WaterEngine]
ReflectionMapSize = 512
SetAtmoshpere = false

[Develop]
# 0 disable effects compilation, 1 Compile All effects when enabled, 2 Compile modified or missing only, 3 Compile only in menu
CompileEffects = 2
# 0 disable shaders compilation, 1 Compile All shaders when enabled, 2 Compile modified or missing only, 3 Compile only in menu
CompileShaders = 2
# enables hotkeys to print reneder data (may change between versions)
DebugMode = false
# Key (in dx scancodes) to toggle debug log for the frame and the render window
TraceShaders = 25

[Culling]
EnableMainCulling = true
EnableRelfectionCulling = true
CullMinSize = 10.0
CullReflectionMinSize = 100.0

[FlyCam]
Enabled = true
ScrollMultiplier = 2.0
KeyAdd = 78
KeySubtract = 74
StepValue = 1.0

[SleepingMode]
Enabled = false
Mode = 0

[LowHFSound]
HealthEnabled = true
FatigueEnabled = true
HealthCoeff = 0.5
FatigueCoeff = 0.5

[Shaders]
Blood = true
Grass = false
HDR = true
NightEye = true
POM = true
Skin = true
Terrain = true
Water = true
Extra = true

[Effects]
AmbientOcclusion = false
BloodLens = true
Bloom = true
Cinema = true
Coloring = true
DepthOfField = false
GodRays = true
LowHF = true
MotionBlur = false
Rain = true
Snow = true
Sharpening = true
SnowAccumulation = true
Underwater = true
WaterLens = true
WetWorld = true
VolumetricFog = false
ShadowsExteriors = true
ShadowsInteriors = false
Specular = true
Extra = true

[Menu]
TextFont = "Calibri"
TextFontStatus = "Consolas"
TextSize = 22
TextSizeStatus = 12
TextColorNormal = [240, 200, 80]
TextShadowColorNormal = [50, 50, 50]
TextColorSelected = [255, 255, 255]
TextShadowColorSelected = [50, 50, 50]
KeyEnable = 24
KeyUp = 200
KeyDown = 208
KeyLeft = 203
KeyRight = 205
KeyPageUp = 201
KeyPageDown = 209
KeyAdd = 78
KeySubtract = 74
KeySave = 28
KeyEditing = 156

[ShadowsForm]
Activators = true
Actors = true
Apparatus = true
Books = true
Containers = true
Doors = true
Furniture = true
Misc = true
Statics = true
Terrain = true
Trees = true
Lod = false
MinRadius = 10.0
Alpha = true

[ShadowsExterior]
# Shadows engine enabled (true or false)
Enabled = true
# Shadow engine type (DISABLED, VSM, ESM, ESSM)
ShadowMode = "VSM"
# Shadow map resolution (prefers power of 2 sizes)
ShadowMapResolution = 2048
ShadowMapRadius = 8000.0
ShadowMapFarPlane = 32768.0
BlurShadowMaps = true

[ShadowsInterior]
Enabled = false
ShadowMode = 1
ShadowCubeMapResolution = 2048
LightPoints = 4
TorchesCastShadows = true
LightRadiusMult = 1.0
